# Generated by Django 5.1.2 on 2024-10-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='image_url',
        ),
        migrations.AddField(
            model_name='flan',
            name='image',
            field=models.ImageField(default=0, upload_to='flanes/'),
            preserve_default=False,
        ),
    ]
