# Generated by Django 5.1.2 on 2024-10-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_flan_image_url_flan_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='description',
        ),
        migrations.AlterField(
            model_name='flan',
            name='image',
            field=models.ImageField(upload_to='flan_images/'),
        ),
        migrations.AlterField(
            model_name='flan',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
