# Generated by Django 5.1.2 on 2024-10-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_flan_description_alter_flan_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='image',
        ),
        migrations.AddField(
            model_name='flan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flan',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
