# Generated by Django 5.1.2 on 2024-10-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_flan'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
