# Generated by Django 5.1.2 on 2024-10-25 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_flan_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='custumer_email',
            new_name='customer_email',
        ),
    ]
