# Generated by Django 5.1.2 on 2024-10-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_custumer_email_contactform_customer_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ContactFormModelForm',
        ),
    ]
