# Generated by Django 5.1.2 on 2024-10-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
